// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mqzedmzjqlvknzidgxjd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1xemVkbXpqcWx2a256aWRneGpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4ODY4NjgsImV4cCI6MjA3MDQ2Mjg2OH0.aWjmHOCm8-b332mdFZT81DSZ_3nHSPLX1naiY3xS184";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});